name: nixpkgs-update
version: 0.2.0
synopsis: Tool for automatic updating of nixpkgs repository
homepage: https://github.com/ryantm/nixpkgs-update#readme
license: PublicDomain
author: Ryan Mulligan
maintainer: ryan@ryantm.com
copyright: 2018 Ryan Mulligan
category: Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - directory >= 1.3 && < 1.4
  - filepath
  - neat-interpolation >= 0.3 && < 0.4
  - optparse-applicative
  - regex-applicative
  - shelly >= 1.6 && < 1.8
  - text
  - time >= 1.8 && < 1.10
  - errors
  - mtl

executables:
  nixpkgs-update:
    source-dirs: src
    main: Main.hs

tests:
  doctests:
    main: doctests.hs
    ghc-options: -threaded
    source-dirs: test
    dependencies:
      - doctest >= 0.11.1 && < 0.16
